### ISSUE TITLE
Test the Kubernetes Python client to ensure that it can manage Ingress resources

### ISSUE THREAD

**Issue by AlexIoannides** [bodywork-ml/bodywork-core#41]
Use [this](https://github.com/kubernetes-client/python/blob/v12.0.0/kubernetes/docs/ExtensionsV1beta1Api.md#create_namespaced_ingress) to implement this equivalent of,

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-scoring-service
  namespace: ml-workflow
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /scoring-service(/|$)(.*)
        backend:
          serviceName: bodywork-ml-pipeline-project--stage-2-deploy-scoring-service
          servicePort: 5000
```

When deploying the `bodywork-ml-pipeline-project` template project and using the Kubernetes NGINX ingress controller as deployed using [this](https://kubernetes.github.io/ingress-nginx/deploy/#aws).
